customhost = "employee.cujavq47oj5k.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "employee123"
customregion = "us-east-1"
